### ISSUE TITLE
using "int" for number types risks overflow

### ISSUE THREAD

**Issue by andoks** [twpayne/go-jsonstruct#15]
I am trying to communicate with an API that returns (and receives) integers may be up to [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). This may [overflow](https://go.dev/play/p/qe4lGWrbriv) if one is compiling on a machine where go decides to use 32bit integers for int.

Could perhaps go-jsonstruct create such fields with int64 type instead?

**Comment by andoks** [comment]
Maybe this could be done relatively easily by adding a "-inttype" flag, and using [WithIntType](https://github.com/twpayne/go-jsonstruct/blob/9f17595a678c3d288e03da65a4be880224ed3d7f/generator.go#L89C6-L89C17)?

**Comment by twpayne** [comment]
Yup!

```console
$ echo '{"k":1}' | go run ./cmd/gojsonstruct -inttype=int64
package main

type T struct {
        K int64 `json:"k"`
}
```

I've tagged `v2.2.0` which includes this.

**Comment by andoks** [comment]
Thanks @twpayne! :tada: :tada: :tada: 

15min turnaround for a new feature must be some kind of record I reckon :sweat_smile:
