### ISSUE TITLE
It is possible to write a multi-line comment?

### ISSUE THREAD

**Issue by cee-dub** [twpayne/go-jsonstruct#22]
Thank you for this tool, I'm finding it helpful!

`go help generate` suggests

```
To convey to humans and machine tools that code is generated,
generated source should have a line that matches the following
regular expression (in Go syntax):

	^// Code generated .* DO NOT EDIT\.$

This line must appear before the first non-comment, non-blank
text in the file.
```

But I'm having trouble figuring out how to add this comment using the available options. This just includes a literal `\n` in the output:

```console
$ echo '{"some": "json"}' | gojsonstruct --package-comment="Code generated by gojsonstruct; DO NOT EDIT.\n\n// Package main does things."
```
```go
// Code generated by gojsonstruct; DO NOT EDIT.\n\n// Package main does things.
package main

type T struct {
	Some string `json:"some"`
}
```

Ideally I could generate this, instead:
``` go
// Code generated by gojsonstruct; DO NOT EDIT.

// Package main does things.
package main

type T struct {
	Some string `json:"some"`
}
```

The same should be possible for the `--type-comment`. Maybe I'm just missing some fancy shell incantations?

**Comment by twpayne** [comment]
Hmm, I am also unable to pass a multiline string as a argument. I think this is simply a limitation of most shells.

#23 adds a `--file-header` flag so you can use:

```console
$ echo '{"some": "json"}' | gojsonstruct --file-header="// Code generated by gojsonstruct; DO NOT EDIT." --package-comment="Package main does things."
// Code generated by gojsonstruct; DO NOT EDIT.

// Package main does things.
package main

type T struct {
        Some string `json:"some"`
}
```

This is of course limited to single line file headers. Could you test this?

**Comment by cee-dub** [comment]
Thanks for adding this!

I'm a little bit confused that `--file-header` requires the leading `//` where the other `--*-comment` flags do not, but it makes sense in case it needs to be used for pragmas or other things of that nature.
